@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 14 11:20:31 +0100 2023
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim multi_round_hasher_tb_behav -key {Behavioral:sim_1:Functional:multi_round_hasher_tb} -tclbatch multi_round_hasher_tb.tcl -view C:/Users/nicla/Documents/GitHub/ESD3_project/code/sha256_vivado_cmod/passwd_expander_hash_tb_behav.wcfg -view C:/Users/nicla/Documents/GitHub/ESD3_project/code/sha256_vivado_cmod/multi_round_hasher_tb_behav.wcfg -log simulate.log"
call xsim  multi_round_hasher_tb_behav -key {Behavioral:sim_1:Functional:multi_round_hasher_tb} -tclbatch multi_round_hasher_tb.tcl -view C:/Users/nicla/Documents/GitHub/ESD3_project/code/sha256_vivado_cmod/passwd_expander_hash_tb_behav.wcfg -view C:/Users/nicla/Documents/GitHub/ESD3_project/code/sha256_vivado_cmod/multi_round_hasher_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
