#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 09 14:28:16 CET 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim passwd_expander_tb_behav -key {Behavioral:sim_1:Functional:passwd_expander_tb} -tclbatch passwd_expander_tb.tcl -view /home/markus/uni/ESD3_project/code/cmod_sha256/sha256_core_simulation.wcfg -view /home/markus/uni/ESD3_project/code/cmod_sha256/passwd_expander_tb_behav.wcfg -log simulate.log"
xsim passwd_expander_tb_behav -key {Behavioral:sim_1:Functional:passwd_expander_tb} -tclbatch passwd_expander_tb.tcl -view /home/markus/uni/ESD3_project/code/cmod_sha256/sha256_core_simulation.wcfg -view /home/markus/uni/ESD3_project/code/cmod_sha256/passwd_expander_tb_behav.wcfg -log simulate.log

